apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-1
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: { }
            'f:app': { }
        'f:spec':
          'f:progressDeadlineSeconds': { }
          'f:replicas': { }
          'f:revisionHistoryLimit': { }
          'f:selector':
            'f:matchLabels':
              .: { }
              'f:app': { }
          'f:strategy':
            'f:rollingUpdate':
              .: { }
              'f:maxSurge': { }
              'f:maxUnavailable': { }
            'f:type': { }
          'f:template':
            'f:metadata':
              'f:labels':
                .: { }
                'f:app': { }
            'f:spec':
              'f:containers':
                'k:{"name":"deltagreencharactercreator-1"}':
                  .: { }
                  'f:image': { }
                  'f:imagePullPolicy': { }
                  'f:name': { }
                  'f:resources': { }
                  'f:terminationMessagePath': { }
                  'f:terminationMessagePolicy': { }
              'f:dnsPolicy': { }
              'f:restartPolicy': { }
              'f:schedulerName': { }
              'f:securityContext': { }
              'f:terminationGracePeriodSeconds': { }
      manager: GoogleCloudConsole
      operation: Update
      time: '2021-07-08T15:27:10Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: { }
            'f:deployment.kubernetes.io/revision': { }
        'f:status':
          'f:availableReplicas': { }
          'f:conditions':
            .: { }
            'k:{"type":"Available"}':
              .: { }
              'f:lastTransitionTime': { }
              'f:lastUpdateTime': { }
              'f:message': { }
              'f:reason': { }
              'f:status': { }
              'f:type': { }
            'k:{"type":"Progressing"}':
              .: { }
              'f:lastTransitionTime': { }
              'f:lastUpdateTime': { }
              'f:message': { }
              'f:reason': { }
              'f:status': { }
              'f:type': { }
          'f:observedGeneration': { }
          'f:readyReplicas': { }
          'f:replicas': { }
          'f:updatedReplicas': { }
      manager: kube-controller-manager
      operation: Update
      time: '2021-07-08T15:27:13Z'
  name: nginx-1
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
        - image: >-
            gcr.io/excellent-range-307103/github.com/parkerthompson/deltagreencharactercreator
          imagePullPolicy: IfNotPresent
          name: deltagreencharactercreator-1